Repository LLMany/LLMany, pull requests merged in 2024-12, with the labels that each got.

#51 Updated all_chats_request and test_all_chats_request
  backend/llmany_backend/requests/all_chats_request.py
  backend/tests/tests_requests/test_all_chats_request.py
Labels: enhancement

#50 Add tests for request handler
  backend/llmany_backend/request_handler.py
  backend/llmany_backend/requests/__init__.py
  backend/tests/test_request_handler.py
Labels: enhancement

#54 Fixed request imports for test_request_handler, and an overlapping pa…
  backend/llmany_backend/requests/__init__.py
  backend/tests/test_request_handler.py
Labels: bug

#56 Added CONTRIBUTING.md with description on how to install pre-commit
  CONTRIBUTING.md
Labels: documentation

#61 Improve mypy precommit
  .pre-commit-config.yaml
  run-mypy.sh
Labels: bug

#62 Added a working version of OpenAIHandler, with basic message sending
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  backend/llmany_backend/__init__.py
  backend/llmany_backend/model_handlers/__init__.py
  backend/llmany_backend/model_handlers/openai_handler.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/tests_model_handlers/test_openai_handler.py
Labels: enhancement

#57 Added first version of SQLiteHandler
  backend/llmany_backend/database_handler.py
  backend/llmany_backend/database_handler_factory.py
  backend/llmany_backend/database_handlers/__init__.py
  backend/llmany_backend/database_handlers/sqlite_handler.py
  backend/tests/tests_database_handlers/test_sqlite_handler.py
Labels: enhancement

#63 Fixed mypy pre-commit hook, and fixed mypy errors
  backend/llmany_backend/model_handler.py
  backend/llmany_backend/model_handler_factory.py
  backend/llmany_backend/model_handlers/anthropic_handler.py
  backend/llmany_backend/model_handlers/google_handler.py
  backend/llmany_backend/model_handlers/openai_handler.py
  backend/llmany_backend/request.py
  backend/llmany_backend/request_handler.py
  backend/llmany_backend/requests/all_chats_request.py
  backend/llmany_backend/requests/chat_history_request.py
  backend/llmany_backend/requests/delete_chat_request.py
  backend/llmany_backend/requests/message_request.py
  backend/llmany_backend/requests/new_chat_request.py
  run-mypy.sh
Labels: bug, enhancement

#66 Add request handler
  API.md
  backend/llmany_backend/request_handler.py
  backend/llmany_backend/requests/message_request.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/conftest.py
  backend/tests/test_request_handler.py
  backend/tests/tests_database_handlers/test_sqlite_handler.py
Labels: enhancement

#68 Fixed RequestHandler tests failing due to invalid parameters
  backend/llmany_backend/request.py
  backend/llmany_backend/requests/all_chats_request.py
  backend/llmany_backend/requests/chat_history_request.py
  backend/llmany_backend/requests/delete_chat_request.py
  backend/llmany_backend/requests/message_request.py
  backend/tests/test_request_handler.py
Labels: bug

#78 Add sqlite handler finish
  backend/llmany_backend/database_handler.py
  backend/llmany_backend/database_handlers/sqlite_handler.py
  backend/llmany_backend/requests/message_request.py
  backend/tests/tests_database_handlers/test_sqlite_handler.py
Labels: enhancement

#85 Added desing of api requests
  API.md
Labels: enhancement

#84 Added api key methods to DatabaseHandler and SQLiteHandler, and added…
  backend/llmany_backend/database_handler.py
  backend/llmany_backend/database_handlers/sqlite_handler.py
  backend/tests/tests_database_handlers/test_sqlite_handler.py
Labels: enhancement

#79 fixed tests for sql handler
  backend/tests/tests_database_handlers/test_sqlite_handler.py
Labels: enhancement
