Repository LLMany/LLMany, pull requests merged in 2025-01, with the labels that each got.

#90 Add model handler factory
  backend/llmany_backend/model_handler_factory.py
  backend/llmany_backend/model_handlers/__init__.py
  backend/llmany_backend/model_handlers/anthropic_handler.py
  backend/llmany_backend/model_handlers/google_handler.py
  backend/llmany_backend/requests/message_request.py
  backend/tests/test_model_handler_factory.py
Labels: enhancement

#91 Fixed test failing due to missing parameter
  backend/tests/test_database_handler_factory.py
Labels: enhancement

#94 fixed test
  backend/tests/tests_requests/test_message_request.py
Labels: bug

#97 Added api key requests to RequestHandler, refactored RequestHandler t…
  backend/llmany_backend/request_handler.py
  backend/llmany_backend/requests/__init__.py
  backend/llmany_backend/requests/check_api_key_request.py
  backend/tests/test_request_handler.py
Labels: enhancement

#93 Design check_api_key
  API.md
Labels: enhancement

#98 Add google handler
  backend/llmany_backend/model_handler.py
  backend/llmany_backend/model_handlers/google_handler.py
  backend/llmany_backend/model_handlers/openai_handler.py
  backend/mypy.ini
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/tests_model_handlers/test_google_handler.py
  backend/tests/tests_model_handlers/test_openai_handler.py
Labels: enhancement

#101 Fixed circular requests that happened for some magic reason, due to r…
  backend/llmany_backend.db
  backend/llmany_backend/__init__.py
  backend/llmany_backend/llmany_requests/__init__.py
  backend/llmany_backend/llmany_requests/add_api_key_request.py
  backend/llmany_backend/llmany_requests/all_chats_request.py
  backend/llmany_backend/llmany_requests/chat_history_request.py
  backend/llmany_backend/llmany_requests/check_api_key_request.py
  backend/llmany_backend/llmany_requests/delete_chat_request.py
  backend/llmany_backend/llmany_requests/message_request.py
  backend/llmany_backend/llmany_requests/new_chat_request.py
  backend/llmany_backend/llmany_requests/remove_api_key_request.py
  backend/llmany_backend/model_handlers/anthropic_handler.py
  backend/llmany_backend/request_handler.py
  backend/tests/test_request_handler.py
  backend/tests/tests_requests/test_add_api_key_request.py
  backend/tests/tests_requests/test_all_chats_request.py
  backend/tests/tests_requests/test_chat_history_request.py
  backend/tests/tests_requests/test_delete_chat_request.py
  backend/tests/tests_requests/test_message_request.py
  backend/tests/tests_requests/test_new_chat_request.py
  backend/tests/tests_requests/test_remove_api_key_request.py
Labels: bug

#106 Fixes after reqeust name change
  .gitignore
  backend/llmany_backend.db
  backend/tests/tests_requests/test_check_api_key_request.py
Labels: bug, enhancement

#112 Add qwen handler
  backend/llmany_backend/model_handler_factory.py
  backend/llmany_backend/model_handlers/__init__.py
  backend/llmany_backend/model_handlers/qwen_handler.py
  backend/tests/tests_model_handlers/test_qwen_handler.py
Labels: enhancement

#119 Fix stdout flush
  backend/llmany_backend/llmany_requests/all_chats_request.py
  backend/llmany_backend/llmany_requests/chat_history_request.py
  backend/llmany_backend/llmany_requests/check_api_key_request.py
  backend/llmany_backend/llmany_requests/delete_chat_request.py
  backend/llmany_backend/llmany_requests/message_request.py
  backend/llmany_backend/llmany_requests/new_chat_request.py
  backend/tests/tests_requests/test_message_request.py
Labels: bug

#118 Add huggingface handler
  backend/llmany_backend/model_handler_factory.py
  backend/llmany_backend/model_handlers/__init__.py
  backend/llmany_backend/model_handlers/deepseek_handler.py
  backend/llmany_backend/model_handlers/huggingface_handler.py
  backend/mypy.ini
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/tests_model_handlers/test_deepseek_handler.py
  backend/tests/tests_model_handlers/test_huggingface_handler.py
Labels: enhancement

#122 Fix google messages
  backend/llmany_backend/llmany_requests/message_request.py
Labels: bug

#123 Fixed Google models not working due to wrong names in history
  backend/llmany_backend/model_handlers/google_handler.py
Labels: bug

#124 Fixed tests
  backend/tests/tests_requests/test_all_chats_request.py
  backend/tests/tests_requests/test_chat_history_request.py
  backend/tests/tests_requests/test_check_api_key_request.py
  backend/tests/tests_requests/test_message_request.py
  backend/tests/tests_requests/test_new_chat_request.py
Labels: bug
